### ISSUE TITLE
uploader_callsign

### ISSUE THREAD

**Issue by ve3gtc** [projecthorus/sondehub-infra#101]
uploader_callsign is a mandatory field. 

However, uploader_callsign is not always the callsign of the station which received the telemtry transmission. Take WSPR for example, the uploader could be anyone whereas the station receiving the transmission is identified separately in the WSPR transmission.

It is important to know who is uploading data. Would it not also have some value in being to identify the actual receiving station in this example for data from a WSPR transmission? Perhaps an optional field to identify whenever the receiving station is not the same as the uploader_callsign.

WSPR also contains some additional metadata such as WSJT-X version, drift, etc. There me be some value in being able to include these additional bits of data. 

cheers, Graham ve3gtc

**Comment by darksidelemm** [comment]
Uploader callsign, position, and software version / radio info is handled on a packet-by-packet basis. 
For the WSPR case, I recommend using the WSPR receiver station callsign as the uploader callsign. 
For software version, I would use the software name of the WSPR-SondeHub gateway. You could suffix this with additional information about the receivers software (e.g. WSJT-X version).

If multiple stations received the same packet, then I would re-upload multiple times with the different receiver information, which will result in the information for each receiver showing up on SondeHub-Amateur.

**Comment by darksidelemm** [comment]
As for the drift field, well you *can* add arbitrary fields to uploads (so long as they don't clash with any existing fields!). So you *could* add this as a "wspr_drift" field if you wanted to.

**Comment by xssfox** [comment]
For APRS we use the "path" field to log intermediate stations and I think we set the upload_callsign to the station which was first on the path (eg the one that heard it first and not an intermediate).
