### ISSUE TITLE
DFM Z-Check altitude resulting in landing positions list for high elevation US states (The Colorado Problem)

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-infra#106]
Getting reports that the Z-check is resulting in packets near landing being dropped (due to not enough packets) in some locations in the US. These locations are where ground level is > 1km ASL, so the Z-check is still used.

The Z-check threshold altitude should probably be increased. I'd suggest 2500m as a start, as this will ensure its higher than the mean elevation of Colorado (Ref: https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_elevation )

**Comment by TheSkorm** [comment]
changed to 2500
