### ISSUE TITLE
Implement telemetry_hidden field and automatically apply this to uploads from uploader_callsign containing 'MYCALL','4FSKTEST','4FSKTEST-V2'

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-infra#107]
This will prompt users to change the callsign in various uploader software to something unique.

**Comment by darksidelemm** [comment]
It may be better to add a tag into the telemetry, something like `{'telemetry_hidden':True}`, and then have a setting (enabled by default) on the tracker to ignore any incoming telemetry with this set. 

This hidden tag could also be applied to 4FSKTEST/4FSKTEST-V2 payloads, and maybe even payloads with the 'dev' tag set?

**Comment by darksidelemm** [comment]
Almost there. (My fault, bad description)

We also need to apply this flag if the uploader_callsign is "MYCALL". Currently we check payload_callsign for "MYCALL"

**Comment by xssfox** [comment]
@darksidelemm did you end fixing this?

**Comment by darksidelemm** [comment]
Yep, fixed in https://github.com/projecthorus/sondehub-infra/commit/85987eaf0864a9f3d0e2c1b4afa02d1726bdf00e
