### ISSUE TITLE
Block rdz_ttgo_sonde v0.9.2

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-infra#109]
rdz_ttgo_sonde 0.9.2 (from September 2022) has some known issues, including DFM misidentification: https://github.com/dl9rdz/rdz_ttgo_sonde/issues/361

These have since been fixed (in rdz dev version 20230427).

We should block uploads (at least DFM) from any older versions of rdz_ttgo_sonde, especially from the old master version. Unsure how feasible it is to block old dev versions.

**Comment by xssfox** [comment]
<img width="1195" alt="image" src="https://github.com/projecthorus/sondehub-infra/assets/59047654/7eeea334-beea-49e0-bbc3-d8883bfe0e78">
There are a lot of 0.9.2 users still :/

**Comment by xssfox** [comment]
@darksidelemm do ttgo's report the error message when sondehub blocks them? I'm thinking we start with DFM block first
