### ISSUE TITLE
Put mandatory fields up front in CSV output

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-infra#110]
Currently the CSV field names are produced in a random order (except for datetime which is up front).
We should probably put the mandatory fields (callsign, lat, lon, alt) at the start of the field list so at least they are somewhat consistent. Everything else can come after that.

Code where datetime is moved to the front is here: https://github.com/projecthorus/sondehub-infra/blob/main/lambda/query_ham/__init__.py#L375
Should be a case of doing the same for callsign, lat, lon, alt.

**Comment by TheSkorm** [comment]
I think this is done?
