### ISSUE TITLE
Predict Update doesn't seem to ignore null positions

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-infra#145]
The predictor code seems to make use of positions that have null position (e.g. lat/lon=0), resulting in dodgy ascent rate calculations if the payload has poor GPS lock.

The query used to get recent positions for a payload should probably:
- Filter out any positions where a 'sats' variable exists, and is equal to 0
- Filter out any positions with a lat/lon both equal to 0.0
https://github.com/projecthorus/sondehub-infra/blob/main/lambda/ham_predict_updater/__init__.py#L466

**Comment by TheSkorm** [comment]
For the moment I've just set it to filter if either lat or lon is exactly 0. I think in practice it's unlikely we'll ever receive exactly 0 from the sondes.
