### ISSUE TITLE
Missing "descending" field in Prediction Data?

### ISSUE THREAD

**Issue by ZigiWalter** [projecthorus/sondehub-infra#17]
Hi,

In the previous HubHab API (https://legacy-snus.habhub.org/tracker/get_predictions.php?vehicles=), the prediction data included an extremely useful "descending" field (obviously, the predication is much more accurate after the balloon bursts).
I don't see that field in the new API.

Will it be possible to add it? Or maybe it's already there and I've missed it somehow...?

Thanks.

**Comment by darksidelemm** [comment]
I guess I have to ask... why are you polling the trackers predictions API? This is meant to be used by the tracker.

**Comment by ZigiWalter** [comment]
It's pulled by some script that sends a notification upon a predicted close landing.
What would be the alternative you had in mind?

**Comment by darksidelemm** [comment]
Polling it is probably fine I guess... The results are cached so I doubt it adds any extra load. @TheSkorm ?

Otherwise you'd need to query Tawhiri for predictions yourself.

**Comment by ZigiWalter** [comment]
To clarify - the polling rate is once every 15 minutes.
If that's even close to creating an issue, please let me know.

Thanks.

**Comment by TheSkorm** [comment]
@ZigiWalter I've added in the field in this commit and rolled out : https://github.com/projecthorus/sondehub-infra/commit/9618ba13cf48037264abef4940c7253b725f1959
Let me know if that works as expected.

Requests are heavily cached so I think we'll be fine, regardless of how often people poll.

**Comment by ZigiWalter** [comment]
Looks very good!
Thanks for handling this so quickly!

**Comment by ZigiWalter** [comment]
BTW, it's not a real problem, but maybe worth fixing:
For some reason, the current "longitude" value (i.e., not the predicted one) returned by that API has only 2 digits after the decimal point, whil;e the "latitude" has around 14...

`[{"vehicle": "S3320993",
"time": "2021-06-18T20:02:15Z",
**"latitude": 32.82045997213572,**
**"longitude": 246.01,**
"altitude": 14267.87,


Thanks.

**Comment by TheSkorm** [comment]
Good catch! For awhile I've wondered why there has been an offset between the prediction and the the actual track, but never got time to explore why. Super easy fix that's been rolled out.

: https://github.com/projecthorus/sondehub-infra/commit/d77bfa8a7cea6938c0516a67ea7f1e545d6b05a8

**Comment by ZigiWalter** [comment]
Thanks again for the second fix!
