### ISSUE TITLE
API's "Sonde Serial" vs. radiosonde_auto_rx "Sonde ID"

### ISSUE THREAD

**Issue by ZigiWalter** [projecthorus/sondehub-infra#19]
Hi,

I'm quite sure it was discussed in the past, but could not find the answer:
What's the recommended way to convert the sonde "ID" value used in radiosonde_auto_rx packet summary to the "serial" key expceted by the sondehub API?
It seems that for some types they are the same (e.g. Vaisala), but for IMET, the ID also includes the type while the serial key shouldn't (so "IMET-A6C9113D" needs to be looked up as "A6C9113D").

Is there a generic conversion or is it actually type-specific? Maybe I can simply use whatever-after-the-last dash (if any) in the sonde ID as the API's serial?

Thanks.

**Comment by darksidelemm** [comment]
If there's a type code at the start, remove it and use everything after the -.

There's a regex here to do it: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/autorx/utils.py#L143

**Comment by ZigiWalter** [comment]
Got it. Thanks!
