### ISSUE TITLE
Add sonde serial option to predictor / reverse predictor query

### ISSUE THREAD

**Issue by TheSkorm** [projecthorus/sondehub-infra#27]
It would be nice to be able to show old predictions for historic sondes

**Comment by TheSkorm** [comment]
https://discord.com/channels/734090820684349521/811884919575150623/896536984493907988

**Comment by TheSkorm** [comment]
@LukePrior I think this is already the case
both https://api.v2.sondehub.org/predictions?vehicles=S4951564 and https://api.v2.sondehub.org/predictions/reverse?vehicles=S4951564 work for me

**Comment by LukePrior** [comment]
Lol too easy.

**Comment by LukePrior** [comment]
Thanks implemented here: https://github.com/projecthorus/sondehub-tracker/pull/200
