### ISSUE TITLE
/recovered API Changes Wishlist

### ISSUE THREAD

**Issue by LukePrior** [projecthorus/sondehub-infra#32]
**Allow multiple serials as a list for input**

- The current API only allows a single serial as string, would be handy to make it accept a list of strings or a single string,
- Will make it easier to implement future features on the tracker including visualising launches from a specific site.

**Recovery Statistics Endpoint**

- The recovery statistics used to be generated by downloading all the recoveries every time the site was loaded but as this dataset grew it was no longer feasible.
- It would be good to have a new endpoint that would return the information previously currently displayed so total number of recoveries (with counts for success and no success), total number of unique callsigns, and top 5 callsigns.
- It would be extra nice if you could provide days or date range as an optional field if you want statistics to be generated for the last week, month, etc.

**Comment by TheSkorm** [comment]
The first of this should be done now :). You can provide a comma separated list of serials eg `https://api.v2.sondehub.org/recovered?serial=S1321065,010-2-12771`

**Comment by TheSkorm** [comment]
And stats up at https://api.v2.sondehub.org/recovered/stats

**Comment by LukePrior** [comment]
Thanks implemented here: https://github.com/projecthorus/sondehub-tracker/pull/200
