### ISSUE TITLE
Launch site API not in swagger

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-infra#34]
The API URL is: https://api.v2.sondehub.org/sites

Response type is gzipped JSON:

```
{
  "-1": {
    "descent_std": 2.5,
    "rs_types": [
      "41"
    ],
    "@version": "1",
    "burst_samples": 52,
    "station": "-1",
    "position": [
      144.947375,
      -37.689883
    ],
    "descent_rate": 5.7,
    "@timestamp": "2021-11-23T22:08:57.372Z",
    "station_name": "Melbourne BoM Training Annex (Training and Ozonesondes) (Australia)",
    "alt": 119,
    "burst_std": 5382,
    "descent_samples": 48,
    "burst_altitude": 28068
  },
  etc...
}
```

**Comment by TheSkorm** [comment]
@LukePrior can you provide details on how rs_types and times work?

**Comment by LukePrior** [comment]
> @LukePrior can you provide details on how rs_types and times work?

`rs_types` are based on the codes used by the WMO to identify sondes. I've got two lists of known sondes which we can and cannot decode.

**Supported**
```
    "07":"iMet-1", "11":"LMS6-403", "13":"RS92", "14":"RS92", "17":"DFM-09", "18":"DFM-06", "19":"MRZ-N1", "22":"RS-11G", "23":"RS41", "24":"RS41", "34":"iMet-4", "35":"iMS-100", "41":"RS41", "42":"RS41", "52":"RS92-NGP", "54":"DFM-17", "62":"MRZ-3MK", "63":"M20", "77":"M10", "82":"LMS6-1680", "84":"iMet-54"
```

**Unsupported**
```
    "15":"PAZA-12M", "16":"PAZA-22", "20":"MK3", "21":"1524LA LORAN-C/GL5000", "26":"SRS-C34", "27":"AVK-MRZ", "28":"AVK–AK2-02", "29":"MARZ2-2", "30":"RS2-80", "33":"GTS1-2/GFE(L)", "45":"CF-06", "58":"AVK-BAR", "59":"M2K2-R", "68":"AVK-RZM-2", "69":"MARL-A/Vektor-M-RZM-2", "73":"MARL-A", "78":"RS90", "80":"RS92", "88":"MARL-A/Vektor-M-MRZ", "89":"MARL-A/Vektor-M-BAR", "97":"iMet-2", "99":"iMet-2"
```

They can either be provided as a single list of strings containing one or more codes: `"rs_types": ["41", "07"]`

If the sondes always transmit on the same known frequency this can also be provided by having each code within a nested list containing the code and frequency: `"rs_types": [["41", "404.300"], ["07", "404.200"]]`

Times is a list of strings where each string represents a UTC launch schedule created in the following format:

- 0:00:00 (day:hour:minute)

When day is set to 0 it means that the following launch time occurs every day
When day is set to 1-7 it means the following launch occurs weekly on that day (Monday - Sunday)

Hour is expressed in 24 hour time and we stick with 3 hour windows to keep things simple so `03, 06, 09, 12, 15, 18, 21, 24`

Minutes can be any value between 0 and 60 but we always leave this value at 00 (in the tracker we subtract 45 minutes from the time to generate predictions).
