### ISSUE TITLE
Add block-list for chase car uploads.

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-infra#50]
We're seeing a lot of chase car position uploads from callsign 'CHANGEME_RDZTTGO', which are all from misconfigured rdz_ttgo_sonde devices. These jump around the map and just cause annoyance.

It would be useful if we had a block-list somewhere for chase-car callsigns. Something similar for station position and telemetry uploads would probably not be a bad idea either.

**Comment by TheSkorm** [comment]
Fixed in b291a749939a0ad26704a973f7cedcc3f5ea05b6
