### ISSUE TITLE
Grafana dashboard mixing telemetry from multiple payloads

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-infra#91]
Example here: https://grafana.v2.sondehub.org/d/HJgOZLq7k/basic?var-Payload=PD2SDV&from=1672138285000&to=1672155890000&orgId=1

The two payloads that are being mixed are: PD2SDV and PD2SDV-LORA.

This might be some query issue?

**Comment by darksidelemm** [comment]
OK... this seems to be an issue with `==` vs `:`

Using `payload_callsign.keyword == "$Payload"` matches anything starting with $Payload. 
Using `payload_callsign.keyword : "$Payload"` matches for $Payload specifically (the intended behaviour).

I've modified the 'Basic' dashboard. Will close this once all other dashboards are fixed.

**Comment by TheSkorm** [comment]
This appears to be done
