### ISSUE TITLE
Missing pressure field in historical data (s3 bucket data source)

### ISSUE THREAD

**Issue by jdenoy** [projecthorus/sondehub-infra#92]
Hello,

i've been looking at a couple of historical data for a couple of sondes like '104-2-11264', and I cannot find pressure data in the s3 buckets even though it's part of the telemetry_format. Ex of data : 

``` {
    "alt": 413.78,
    "datetime": "2022-12-30T13:38:05.000Z",
    "frame": 1672407485,
    "heading": 38.20277,
    "humidity": 93.64,
    "lat": 49.12195,
    "lon": 0.64135,
    "manufacturer": "Meteomodem",
    "position": "49.12195,0.64135",
    "serial": "104-2-11264",
    "software_name": "SondeMonitor",
    "software_version": "6.2.8.2",
    "temp": 12.27,
    "time_received": "2022-12-30T13:38:05Z",
    "type": "M10",
    "upload_time_delta": -1.7,
    "uploader_alt": 135,
    "uploader_callsign": "F21061",
    "uploader_position": "49.0842,0.5917",
    "user-agent": "Amazon CloudFront",
    "vel_h": 16.2504,
    "vel_v": -8.24
  }```
(source : http://sondehub-history.s3.amazonaws.com/serial/104-2-11264.json.gz)

All other xx fields are populated. Is there something missing in the data collection?
The sondehub website shows the pressure, is there a way to regenerate the file with the pressure field populated ?

Txs,
Johan

**Comment by darksidelemm** [comment]
Your example is for a M10 radiosonde, where as far as we are aware, pressure data is not sent in the telemetry. We do have pressure data for some variants of M20 radiosondes.

**Comment by darksidelemm** [comment]
There's some information on what sensor data radiosonde_auto_rx decodes here: https://github.com/projecthorus/radiosonde_auto_rx/#radiosonde-support-matrix

This is not the case for all receiving software that uploads to Sondehub however, some may support less sensor fields.

**Comment by jdenoy** [comment]
Hello Mark, my mistake.
I forgot to check that part, and it explains it all since pressure is calculated from gps altitude in the M10.
Thanks for your time.
